# Generated by Django 6.0.2 on 2026-02-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userprofile_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='device_id',
            field=models.CharField(blank=True, help_text='Unique identifier for the device', max_length=255, null=True, unique=True),
        ),
    ]
