# Generated by Django 6.0.2 on 2026-02-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userprofile_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='baseline_hold_time_sec',
            field=models.IntegerField(blank=True, help_text='Breath hold time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dyspnea_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dyspnea_score',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mep_value',
            field=models.FloatField(blank=True, help_text='MEP value', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mip_value',
            field=models.FloatField(blank=True, help_text='MIP value', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='muscle_strength_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='muscle_strength_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pack_years',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, help_text='Breaths per minute', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smoking_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spo2_level',
            field=models.IntegerField(blank=True, help_text='Oxygen saturation %', null=True),
        ),
    ]
