# Generated by Django 6.0.2 on 2026-02-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userprofile_device_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, help_text='Device identifier', max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('session_duration_sec', models.IntegerField(default=0, help_text='Total session duration in seconds')),
                ('breath_count', models.IntegerField(default=0, help_text='Total breaths in the session')),
                ('completed_cycles', models.IntegerField(default=0, help_text='Cycles completed')),
                ('total_cycles', models.IntegerField(default=10, help_text='Total cycles planned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
