# Generated by Django 5.1.15 on 2026-03-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_trainingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='notes',
            field=models.TextField(blank=True, help_text='Clinical journal notes from patient', null=True),
        ),
    ]
