# Generated by Django 5.1.15 on 2026-03-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_trainingsession_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='exhale_accuracy',
            field=models.IntegerField(default=0, help_text='Exhale accuracy %'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='hold_accuracy',
            field=models.IntegerField(default=0, help_text='Hold accuracy %'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='inhale_accuracy',
            field=models.IntegerField(default=0, help_text='Inhale accuracy %'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='overall_accuracy',
            field=models.IntegerField(default=0, help_text='Overall accuracy %'),
        ),
    ]
